# Unit 2 - Lesson 5: Counted Loops and Making Shapes

# Predict:
# Print a triangle of '#' starting with one and increasing to ten
char = "#"
for count in range(1, 11):
    print(char * count)

# Try this:
# Print the string "--8<--" repeated 10 times consecutively
pattern = "--8<--"
print(pattern * 10)

# Modify 1:
# Show what numbers are generated by range from -5 up to (but not including) 5
for num in range(-5, 5):
    print(num, end=" ")
print()

# Try this:
# Print a decreasing triangle of '#' from 10 down to 1
for count in range(10, 0, -1):
    print("#" * count)

# Modify 2:
# Create a centered pyramid with 5 rows
rows = 5
for i in range(rows):
    spaces = rows - i - 1  # spaces decrease as row increases
    hashes = 2 * i + 1     # hashes increase by 2 each row (odd numbers)
    print(" " * spaces + "#" * hashes)

# Modify 3:
# Create a diamond shape by combining a pyramid and inverted pyramid
rows = 5

# Upper part of diamond (pyramid)
for i in range(rows):
    spaces = rows - i - 1
    hashes = 2 * i + 1
    print(" " * spaces + "#" * hashes)

# Lower part of diamond (inverted pyramid, skip the middle row)
for i in range(rows - 2, -1, -1):
    spaces = rows - i - 1
    hashes = 2 * i + 1
    print(" " * spaces + "#" * hashes)
